src/django_tabler_ng/urls.py
from cgitb import handler
from django.urls import path
from .views import *
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'django_tabler_ng'

urlpatterns = [
    path('sign_in/', auth_views.LoginView.as_view(
        template_name='django_tabler_ng/signin.html'), name='sign_in'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='django_tabler_ng/password_change.html',
        success_url = reverse_lazy('django_tabler_ng:password_change_done')), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='django_tabler_ng/password_change_done.html'), name='password_change_done'),
    path('sign_out/', auth_views.LogoutView.as_view(
        template_name='django_tabler_ng/signout.html'), name='sign_out'),
]

src/django_tabler_ng/forms.py
from django.forms import EmailInput, NumberInput, PasswordInput, Textarea, TextInput, URLInput
from django.utils.safestring import mark_safe

from .bootstrap import get_bootstrap_setting, get_field_renderer, get_form_renderer, get_formset_renderer
from .exceptions import BootstrapError
from .text import text_value
from .utils import add_css_class, render_tag

FORM_GROUP_CLASS = "mb-3"


def render_formset(formset, **kwargs):
    """Render a formset to a Bootstrap layout."""
    renderer_cls = get_formset_renderer(**kwargs)
    return renderer_cls(formset, **kwargs).render()


def render_formset_errors(formset, **kwargs):
    """Render formset errors to a Bootstrap layout."""
    renderer_cls = get_formset_renderer(**kwargs)
    return renderer_cls(formset, **kwargs).render_errors()


def render_form(form, **kwargs):
    """Render a form to a Bootstrap layout."""
    renderer_cls = get_form_renderer(**kwargs)
    return renderer_cls(form, **kwargs).render()


def render_form_errors(form, type="all", **kwargs):
    """Render form errors to a Bootstrap layout."""
    renderer_cls = get_form_renderer(**kwargs)
    return renderer_cls(form, **kwargs).render_errors(type)


def render_field(field, **kwargs):
    """Render a field to a Bootstrap layout."""
    renderer_cls = get_field_renderer(**kwargs)
    return renderer_cls(field, **kwargs).render()


def render_label(content, label_for=None, label_class="form-label", label_title=""):
    """Render a label with content."""
    attrs = {}
    if label_for:
        attrs["for"] = label_for
    if label_class:
        attrs["class"] = label_class
    if label_title:
        attrs["title"] = label_title
    return render_tag("label", attrs=attrs, content=content)


def render_button(
    content,
    button_type=None,
    button_class="btn-primary",
    size="",
    href="",
    name=None,
    value=None,
    title=None,
    extra_classes="",
    id="",
):
    """Render a button with content."""
    attrs = {}
    classes = add_css_class("btn", button_class)
    size = text_value(size).lower().strip()
    if size == "xs":
        classes = add_css_class(classes, "btn-xs")
    elif size == "sm" or size == "small":
        classes = add_css_class(classes, "btn-sm")
    elif size == "lg" or size == "large":
        classes = add_css_class(classes, "btn-lg")
    elif size == "md" or size == "medium":
        pass
    elif size:
        raise BootstrapError('Parameter "size" should be "xs", "sm", "lg" or empty ("{size}" given).'.format(size=size))

    if button_type:
        if button_type not in ("submit", "reset", "button", "link"):
            raise BootstrapError(
                (
                    'Parameter "button_type" should be "submit", "reset", "button", "link" or empty '
                    '("{button_type}" given).'
                ).format(button_type=button_type)
            )
        if button_type != "link":
            attrs["type"] = button_type

    classes = add_css_class(classes, extra_classes)
    attrs["class"] = classes

    if href:
        tag = "a"
        if button_type and button_type != "link":
            raise BootstrapError(
                'Button of type "{button_type}" is not allowed a "href" parameter.'.format(button_type=button_type)
            )
        attrs["href"] = href
        # Specify role for link with button appearance
        attrs.setdefault("role", "button")
    else:
        tag = "button"

    if id:
        attrs["id"] = id
    if name:
        attrs["name"] = name
    if value:
        attrs["value"] = value
    if title:
        attrs["title"] = title
    return render_tag(tag, attrs=attrs, content=mark_safe(content))


def render_field_and_label(field, label, field_class="", label_for=None, label_class="", layout="", **kwargs):
    """Render a field with its label."""
    if layout == "horizontal":
        if not label_class:
            label_class = get_bootstrap_setting("horizontal_label_class")
        if not field_class:
            field_class = get_bootstrap_setting("horizontal_field_class")
        if not label:
            label = mark_safe("&#160;")
        label_class = add_css_class(label_class, "control-label")
    html = field
    if field_class:
        html = '<div class="{field_class}">{html}</div>'.format(field_class=field_class, html=html)
    if label:
        html = render_label(label, label_for=label_for, label_class=label_class) + html
    return html


def render_form_group(content, css_class=FORM_GROUP_CLASS):
    """Render a Bootstrap form group."""
    return '<div class="{css_class}">{content}</div>'.format(css_class=css_class, content=content)


def is_widget_with_placeholder(widget):
    """
    Return whether this widget should have a placeholder.

    Only text, text area, number, e-mail, url, password, number and derived inputs have placeholders.
    """
    return isinstance(widget, (TextInput, Textarea, NumberInput, EmailInput, URLInput, PasswordInput))

src/django_tabler_ng/views.py
#coding: utf-8

from django.shortcuts import render


def error404(request, exception):
    return render(request, 'django_tabler_ng/404.html', status=404)


def error500(request, exception):
    return render(request, 'django_tabler_ng/500.html', status=500)

src/django_tabler_ng/templates/bootstrap5/bootstrap5.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% if 'use_i18n'|bootstrap_setting %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Page title -->
    <title>{% block bootstrap5_title %}django-bootstrap-v5 template title{% endblock %}</title>

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}

    <!-- Bootstrap JavaScript if it is in head -->
    {% if 'javascript_in_head'|bootstrap_setting %}
        {% bootstrap_javascript %}
    {% endif %}

    {% block bootstrap5_extra_head %}{% endblock %}

</head>

<body>
{% block bootstrap5_before_content %}{% endblock %}
{% block bootstrap5_content %} CONTENT {% endblock %}
{% block bootstrap5_after_content %}{% endblock %}

<!-- Bootstrap JavaScript if it is in body -->
{% if not 'javascript_in_head'|bootstrap_setting %}
    {% bootstrap_javascript %}
{% endif %}

{% block bootstrap5_extra_script %}{% endblock %}

</body>

</html>

src/django_tabler_ng/templates/bootstrap5/field_errors.html
{% for text in field_errors %}
    <div class="invalid-feedback">{{ text }}</div>
{% endfor %}

src/django_tabler_ng/templates/bootstrap5/field_help_text.html
{% if field_help %}
    <small class="form-text text-muted">{{ field_help }}</small>
{% endif %}

src/django_tabler_ng/templates/bootstrap5/form_errors.html
{% load i18n %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="{% trans 'close' %}"></button>
    {% for error in errors %}
        {{ error }}{% if not forloop.last %}<br>{% endif %}
    {% endfor %}
</div>

src/django_tabler_ng/templates/bootstrap5/messages.html
{% load i18n bootstrap5 %}
{% for message in messages %}
    <div class="{{ message|bootstrap_message_classes }} alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="{% trans 'close' %}"></button>
        {{ message }}
    </div>
{% endfor %}

src/django_tabler_ng/templates/bootstrap5/pagination.html
{% load bootstrap5 %}
{% with bpurl=bootstrap_pagination_url|default:"" %}

    <ul class="{{ pagination_css_classes }}">

        <li class="prev page-item{% if current_page == 1 %} disabled{% endif %}">
            <a class="page-link" href="{% if current_page == 1 %}#{% else %}{% bootstrap_url_replace_param bpurl parameter_name 1 %}{% endif %}">
                &laquo;
            </a>
        </li>

        {% if pages_back %}
            <li class="page-item">
                <a class="page-link" href="{% bootstrap_url_replace_param bpurl parameter_name pages_back %}">&hellip;</a>
            </li>
        {% endif %}

        {% for p in pages_shown %}
            <li class="page-item{% if current_page == p %} active{% endif %}">
                <a class="page-link" href="{% if current_page == p %}#{% else %}{% bootstrap_url_replace_param bpurl parameter_name p %}{% endif %}">
                    {{ p }}
                </a>
            </li>
        {% endfor %}

        {% if pages_forward %}
            <li class="page-item">
                <a class="page-link" href="{% bootstrap_url_replace_param bpurl parameter_name pages_forward %}">&hellip;</a>
            </li>
        {% endif %}

        <li class="last page-item{% if current_page == num_pages %} disabled{% endif %}">
            <a class="page-link" href="{% if current_page == num_pages %}#{% else %}{% bootstrap_url_replace_param bpurl parameter_name num_pages %}{% endif %}">
                &raquo;
            </a>
        </li>

    </ul>

{% endwith %}

src/django_tabler_ng/templates/bootstrap5/widgets/radio_select_button_group.html
<div{% if widget.attrs.id %} id="{{ widget.attrs.id }}"{% endif %} class="btn-group" role="group">
  {% for group, options, index in widget.optgroups %}
    {% for option in options %}
      <input type="{{ option.type }}" class="{{ widget.attrs.class|add:' btn-check' }}" autocomplete="off" name="{{ option.name }}" id="{{ option.attrs.id }}"{% if option.value != None %} value="{{ option.value|stringformat:'s' }}"{% if option.attrs.checked %} checked="checked"{% endif %}{% endif %}{% if widget.required %} required{% endif %}>
      <label class="btn btn-outline-primary" for="{{ option.attrs.id }}">{{ option.label }}</label>
    {% endfor %}
  {% endfor %}
</div>

src/django_tabler_ng/templates/django_tabler_ng/base.html
{% load static %}
<!doctype html>
{% load bootstrap5 %}
{% if 'use_i18n'|bootstrap_setting %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}" dir="ltr" meta="">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <meta http-equiv="Content-Language" content="en" />
        <meta name="msapplication-TileColor" content="#2d89ef" />
        <meta name="theme-color" content="#4188c9" />
        <meta name="apple-mobile-web-app-status-bar-style"
              content="black-translucent"/>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="HandheldFriendly" content="True" />
        <meta name="MobileOptimized" content="320" />
        <link rel="icon" href="{% static "img/favicon.ico" %}" type="image/x-icon"/>
        <link rel="shortcut icon"
              type="image/x-icon"
              href="{% static "img/favicon.ico" %}"/>
        <title>
            {% block bootstrap5_title %}django-bootstrap-v5 template title{% endblock %}
        </title>
        <!-- CSS files -->
        <link href="{% static "css/tabler.min.css" %}" rel="stylesheet"/>
        <link href="{% static "css/tabler-flags.min.css" %}" rel="stylesheet"/>
        <link href="{% static "css/tabler-payments.min.css" %}" rel="stylesheet"/>
        <link href="{% static "css/tabler-vendors.min.css" %}" rel="stylesheet"/>
        <!-- Bootstrap JavaScript if it is in head -->
        {% if 'javascript_in_head'|bootstrap_setting %}
            {% bootstrap_javascript %}
        {% endif %}
        {% block extra_css %}
        {% endblock extra_css %}
        {% block bootstrap5_extra_head %}{% endblock %}
    </head>
    <body class="{% block body_class %} {% endblock body_class %}">
        {% block bootstrap5_before_content %}{% endblock %}
        {% block bootstrap5_content %}{% endblock %}
        {% block bootstrap5_after_content %}{% endblock %}
        <!-- Tabler Core -->
        <script src="{% static "js/tabler.min.js" %}" defer></script>
        <!-- Bootstrap JavaScript if it is in body -->
        {% if not 'javascript_in_head'|bootstrap_setting %}
            {% bootstrap_javascript %}
        {% endif %}
        {% block bootstrap5_extra_script %}{% endblock %}
    </body>
</html>

src/django_tabler_ng/templates/django_tabler_ng/blank.html
{% extends "django_tabler_ng/base.html" %}
{% load static %}
{% load django_tabler_ng %}
{% block bootstrap5_content %}
  <div class="page">
    <!-- Navbar -->
    <header class="navbar navbar-expand-md navbar-light d-print-none">
      <div class="container-xl">
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbar-menu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
          <a href=".">
            <img src="{% static "img/logo.svg" %}"
                 width="110"
                 height="32"
                 alt="Tabler"
                 class="navbar-brand-image"/>
          </a>
        </h1>
        <div class="navbar-nav flex-row order-md-last">
          <div class="nav-item d-none d-md-flex me-3">
            <div class="btn-list"></div>
          </div>
          <div class="nav-item dropdown">
            <a href="#"
               class="nav-link d-flex lh-1 text-reset p-0"
               data-bs-toggle="dropdown"
               aria-label="Open user menu">
              <span class="avatar avatar-sm"
                    style="background-image: url(https://avatars.dicebear.com/api/initials/:{{ request.user.username }}.svg)"></span>
              <div class="d-none d-xl-block ps-2">
                <div>{{ request.user.username }}</div>
                <div class="mt-1 small text-muted">{{ request.user.first_name }} {{ request.user.last_name }}</div>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
              <a href="{% url "django_tabler_ng:password_change" %}"
                 class="dropdown-item">Change Password</a>
              <div class="dropdown-divider"></div>
              <a href="{% url "django_tabler_ng:sign_out" %}" class="dropdown-item">Logout</a>
            </div>
          </div>
        </div>
      </div>
    </header>
    {% django_tabler_menu %}
    <div class="page-wrapper">
      <!-- Page body -->
      <div class="page-body">
        <div class="container-xl d-flex flex-column justify-content-center">
          {% block page-body %}
          {% endblock %}
        </div>
      </div>
      <footer class="footer footer-transparent d-print-none">
        <div class="container-xl">
          <div class="row text-center align-items-center flex-row-reverse">
            <div class="col-lg-auto ms-lg-auto">
              <ul class="list-inline list-inline-dots mb-0">
                <li class="list-inline-item">
                  <a href="./license.html" class="link-secondary">License</a>
                </li>
              </ul>
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0">
              <ul class="list-inline list-inline-dots mb-0">
                <li class="list-inline-item">
                  Copyright &copy; 2022
                  <a href="." class="link-secondary">Tabler</a>.
                  All rights reserved.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
{% endblock %}

src/django_tabler_ng/templates/django_tabler_ng/password_change.html
{% extends "django_tabler_ng/blank.html" %}
{% load i18n %}
{% block page-body %}
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{% trans "Change password" %}</h3>
            </div>
            <div class="card-body">
                <form method="post" action="">
                    {% csrf_token %}
                    <div class="form-group mb-3 row">
                        <label class="col-3 col-form-label required">{{ form.old_password.label_tag }}</label>
                        <div class="col">
                            <input type="password"
                                   id="old_password"
                                   name="old_password"
                                   class="form-control {% if form.old_password.errors %}is-invalid{% endif %}"
                                   placeholder="Password"/>
                            <div class="invalid-feedback">{{ form.old_password.errors }}</div>
                        </div>
                    </div>
                    <div class="form-group mb-3 row">
                        <label class="col-3 col-form-label required">{{ form.new_password1.label_tag }}</label>
                        <div class="col">
                            <input type="password"
                                   id="new_password1"
                                   name="new_password1"
                                   class="form-control {% if form.new_password1.errors %}is-invalid{% endif %}"
                                   placeholder="Password"/>
                            <div class="invalid-feedback">{{ form.new_password1.errors }}</div>
                            {% if form.new_password1.help_text %}
                                <small class="form-hint">{{ form.new_password1.help_text|safe }}</small>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group mb-3 row">
                        <label class="col-3 col-form-label required">{{ form.new_password2.label_tag }}</label>
                        <div class="col">
                            <input type="password"
                                   id="new_password2"
                                   name="new_password2"
                                   class="form-control {% if form.new_password2.errors %}is-invalid{% endif %}"
                                   placeholder="Password"/>
                            <div class="invalid-feedback">{{ form.new_password2.errors }}</div>
                            {% if form.new_password2.help_text %}
                                <small class="form-hint">{{ form.new_password2.help_text|safe }}</small>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-footer">
                        <button type="submit" class="btn btn-primary">{% trans "Change password" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock page-body %}

src/django_tabler_ng/templates/django_tabler_ng/password_change_done.html
{% extends "django_tabler_ng/blank.html" %}
{% load i18n %}
{% block page-body %}
    <div class="empty">
        <p class="empty-title">{% translate "Your password was changed." %}</p>
    </div>
{% endblock page-body %}

src/django_tabler_ng/templates/django_tabler_ng/signin.html
{% extends "django_tabler_ng/base.html" %}
{% load static %}
{% block body_class %}border-top-wide border-primary d-flex flex-column{% endblock %}
{% block bootstrap5_content %}
  <div class="page page-center">
    <div class="container container-tight py-4">
      <div class="text-center mb-4">
        <a href="." class="navbar-brand navbar-brand-autodark">
          <img src="{% static "img/logo.svg" %}" height="36" alt=""/>
        </a>
      </div>
      <div class="card card-md">
        <div class="card-body">
          {% if form.errors %}
            <h2 class="h2 text-center mb-4">Your username and password didn't match. Please try again.</h2>
          {% else %}
            <h2 class="h2 text-center mb-4">Login to your account</h2>
          {% endif %}
          <form action="{% url "django_tabler_ng:sign_in" %}"
                method="post"
                autocomplete="off"
                novalidate>
            {% csrf_token %}
            <div class="mb-3">
              <label class="form-label">{{ form.username.label_tag }}</label>
              <input type="text"
                     class="form-control"
                     name="username"
                     autofocus=""
                     autocapitalize="none"
                     autocomplete="username"
                     maxlength="150"
                     required=""
                     id="id_username"/>
            </div>
            <div class="mb-2">
              <label class="form-label">
                {{ form.password.label_tag }}
                <span class="form-label-description">
                  <a href="{% url 'django_tabler_ng:password_reset' %}">I forgot password</a>
                </span>
              </label>
              <div class="input-group input-group-flat">
                <input type="password"
                       class="form-control"
                       name="password"
                       autocomplete="current-password"
                       required=""
                       id="id_password"/>
                <span class="input-group-text">
                  <a href="#"
                     class="link-secondary"
                     title="Show password"
                     data-bs-toggle="tooltip"><!-- Download SVG icon from http://tabler-icons.io/i/eye -->
                    <svg xmlns="http://www.w3.org/2000/svg"
                         class="icon"
                         width="24"
                         height="24"
                         viewBox="0 0 24 24"
                         stroke-width="2"
                         stroke="currentColor"
                         fill="none"
                         stroke-linecap="round"
                         stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                      <circle cx="12" cy="12" r="2" />
                      <path d="M22 12c-2.667 4.667 -6 7 -10 7s-7.333 -2.333 -10 -7c2.667 -4.667 6 -7 10 -7s7.333 2.333 10 7" />
                    </svg>
                  </a>
                </span>
              </div>
            </div>
            <div class="mb-2">
              <label class="form-check">
                <input type="checkbox" class="form-check-input"/>
                <span class="form-check-label">Remember me on this device</span>
              </label>
            </div>
            <div class="form-footer">
              <button type="submit" class="btn btn-primary w-100">Sign in</button>
              <input type="hidden" name="next" value="{{ next }}"/>
            </div>
          </form>
        </div>
      </div>
      <div class="text-center text-muted mt-3">
        Don't have account yet? <a href="#" tabindex="-1">Sign up</a>
      </div>
    </div>
  </div>
{% endblock %}

src/django_tabler_ng/templates/django_tabler_ng/signout.html
{% extends "django_tabler_ng/base.html" %}
{% load static %}
{% block body_class %}border-top-wide border-primary d-flex flex-column{% endblock %}
{% block bootstrap5_content %}
  <div class="page page-center">
    <div class="container container-tight py-4">
      <div class="text-center mb-4">
        <a href="." class="navbar-brand navbar-brand-autodark">
          <img src="{% static "img/logo.svg" %}" height="36" alt=""/>
        </a>
      </div>
      <form class="card card-md"
            action="./"
            method="get"
            autocomplete="off"
            novalidate>
        <div class="card-body text-center">
          <div class="mb-4">
            <h2 class="card-title">Logouted</h2>
            <p class="text-muted">See you next time</p>
          </div>
          <div>
            <a href="{% url "django_tabler_ng:sign_in" %}"
               class="btn btn-primary w-100">Leave</a>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}